### PR TITLE
Set DOTNET_NPM_TOOLS environment.

### PR DESCRIPTION
**Pull request by jerboaa**
See https://github.com/redhat-developer/s2i-dotnetcore/pull/35

With this latest 1.0 images built from s2i-dotnetcore will be able to
build/run this sample app. Fails otherwise on the publish step.

### CODE REVIEW

**Comment by jerboaa** [comment]
@tmds PTAL.

**Comment by tmds** [comment]
@jerboaa as part of this, we should revert: https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/055e58d3e4a28184d1e3729ca3cd6d2610f23c17
and change the run script so it calls the base script provided by s2i-dotnetcore (after migrating the database).

Thanks to https://github.com/redhat-developer/s2i-dotnetcore/pull/34 we can also revert https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/6f2f0fd931d648efa9970d50f2dfc3564944bdcd#diff-729af9bfa292ba655a6e0b1452e17dfa. Change can be in this or a separate PR.

**Comment by jerboaa** [comment]
All good suggestions. I'll prepare PRs for them when the time comes. At this point, I'd like to hold off on those until updated images get released. This PR was a means to be 1.0 old (current image) and 1.0 new (unreleased image) compatible. I'll file issues for them so they don't get lost.

**Comment by jerboaa** [comment]
> ... change the run script so it calls the base script provided by s2i-dotnetcore (after migrating the database).

@tmds: How do I do that?

**Comment by jerboaa** [comment]
Revert of https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/055e58d3e4a28184d1e3729ca3cd6d2610f23c17 is tracked with #7.

Revert of https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/6f2f0fd931d648efa9970d50f2dfc3564944bdcd#diff-729af9bfa292ba655a6e0b1452e17dfa is tracked with #20.

**Comment by tmds** [comment]
> @tmds: How do I do that? My understanding is that app/.s2i/bin/run replaces the one from the s2i-dotnetcore builder image.

This should work:
```
exec $STI_SCRIPTS_PATH/run
```

**Comment by jerboaa** [comment]
Thanks, done. OK to merge?

**Comment by jerboaa** [comment]
Thanks for the review. I've merged this.

**Pull request merged**
